### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by diogoguilherme** [pixlpirate/pikmin-map#4]
When searching for a decoration, it either displays that it has it and when you get there it doesn't, or it displays that it doesn't have it anymore and when you get there it does.

Follow the coordinates

-22.887706,-49.982954

-22.983193,-49.867607

**Comment by diogoguilherme** [comment]
As you can see, the map says that there are no ramen Pikmin in the region, but I found them when I was there.

**Comment by diogoguilherme** [comment]
![Screenshot_20241114_155601_Pikmin Bloom](https://github.com/user-attachments/assets/5227f13c-0f9b-4d83-b2b3-1e60aef477ee)
![Screenshot_20241114_155445_Chrome](https://github.com/user-attachments/assets/708e8d78-9c1d-4805-8603-4bb69adbf15a)

**Comment by pixlpirate** [comment]
Hello @diogoguilherme, thank you for taking the time to describe this problem.

It's not really a bug, but rather something to do with the way this application works. 

The game uses at least two data sources: 
- Open Street Map (OSM): For the base maps and most of the geolocated data.
- Foursquare: For some geolocated data. 
This map is based exclusively on data available on OSM, therefore Foursquare data is missing. Maybe that's what's happening in your example.

I could add the foursquare API to this application, but unlike the OSM API, it's not free and it's rather expensive. This wouldn't entirely solve the problem, as some of the decors seem to come from other sources, which are uncertain at the moment.

For more information on this subject, please consult the FAQ section of the [about page](https://pikmin-map.pixelpirate.fr/about#faq).
